#! /bin/sh

bspc config pointer_modifier mod1
bspc config pointer_follows_monitor false
bspc config pointer_follows_focus true
bspc config ignore_ewmh_focus true

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d 1 3 
bspc monitor HDMI-2 -d 2 4 5

bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a firefox desktop='2' follow=false
bspc rule -a discord desktop='3' follow=false
bspc rule -a Steam   desktop='4' state=floating follow=false
bspc rule -a hl2_linux desktop='4' state=fullscreen follow=false
bspc rule -a imv state=floating
bspc rule -a mpv state=floating
bspc rule -a qbittorrent state=floating
firefox &
discord &
picom &
dunst &
/home/elso/.config/polybar/launch.sh &
feh --bg-scale '/home/elso/wallpaper.jpg'
