# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=9999
SAVEHIST=9999
setopt appendhistory
unsetopt beep
bindkey  "^[[1~"   beginning-of-line
bindkey  "^[[4~"   end-of-line
bindkey '^[[1;5C' emacs-forward-word
bindkey '^[[1;5D' emacs-backward-word
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/elso/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
export PATH=/home/elso/.cargo/bin:$PATH
fpath+=("$HOME/.zsh/pure")
autoload -U promptinit; promptinit
prompt pure
alias ls='exa -x --icons -a'
export GIT_EDITOR=micro