# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=9999
SAVEHIST=9999
setopt appendhistory
unsetopt beep
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/elso/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
export PATH=/home/elso/.cargo/bin:$PATH
fpath+=("$HOME/.zsh/pure")
autoload -U promptinit; promptinit
prompt pure
export GIT_EDITOR=micro
#Doesn't open on termite without this, works on multiplexers like tmux without it
alias micro='TERM=xterm-256color micro'
alias lst='exa --icons --all'

#Bindings for homebuttons, has varied for me
bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line
bindkey  "^[[3~"  delete-char
bindkey '^[[1;5C' emacs-forward-word
bindkey '^[[1;5D' emacs-backward-word
bindkey  "^[[1~"   beginning-of-line
bindkey  "^[[4~"   end-of-line